/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    
    'about',
    {
      type: 'category',
      label: '2022',
      items: ['2022/jan', '2022/feb','2022/mar','2022/apr','2022/may','2022/jun','2022/jul','2022/aug','2022/sep','2022/oct','2022/nov','2022/dec'],
    },
    {
      type: 'category',
      label: '2023',
      items: ['2023/jan', '2023/feb','2023/mar','2023/apr','2023/may','2023/jun','2023/jul','2023/aug','2023/sep','2023/oct','2023/nov','2023/dec'],
    },
  ],

};

module.exports = sidebars;
